#pragma config(Sensor, dgtl1,  leftWheel,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftLift,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightWheel,     sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightLift,      sensorQuadEncoder)
#pragma config(Motor,  port1,           leftWheelR,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftWheelF,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightWheelF,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLift1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightLift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightWheelR,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ##### THE ABOVE SECTION WAS GENERATED BY THE SENSORS AND MOTORS CONFIGURATION PANEL OF ROBOTC #####

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Miscellaneous Include.c"
#include "lib\EaseMotor v2.c"
#include "lib\Timers.c"
#include "lib\Speedometer.c"
#include "Configuration.c"
#include "Internal.c"
#include "LCDDisplay.c"

bool flip = false;

task LCD() {
	startTask(LCDDisplay);
	while (true) {
		if (nLCDButtons == (TControllerButtons) 7)
			startTask(LCDDisplay);
		if (flip) {
			bLCDBacklight = !bLCDBacklight;
		}
		wait1Msec(50);
	}
}

void setup() {
	//displayLCDCenteredString(0, "Please step away");
	//displayLCDCenteredString(1, "from the robot");
	//SensorValue[leftLift] = 0;
	//SensorValue[rightLift] = 0;
	//waitSec(0.5);
	//int LastLeftDegree = 0;
	//int LastRightDegree = 0;
	//for (int i = 0; i < 32; i++) {
	//	motor[leftLift1] = -127;
	//	motor[leftLift2] = -127;
	//	motor[rightLift1] = -127;
	//	motor[rightLift2] = -127;
	//	waitSec(0.0625);
	//	if (abs(LastLeftDegree - SensorValue[leftLift]) <= 200)
	//		break;
	//	LastLeftDegree = SensorValue[leftLift];
	//	LastRightDegree = SensorValue[rightLift];
	//}
	//motor[leftLift1] = 0;
	//motor[leftLift2] = 0;
	//motor[rightLift1] = 0;
	//motor[rightLift2] = 0;
	//waitSec(0.5);
	// Set lift encoders to 0
	SensorValue[leftLift] = 0;
	SensorValue[rightLift] = 0;
	startTask(runEaseMotors);
	startTask(extraTimers);
	startTask(speedometer);
	Ease[leftLift1].Bypass = LiftBypass;
	Ease[leftLift2].Bypass = LiftBypass;
	Ease[rightLift1].Bypass = LiftBypass;
	Ease[rightLift2].Bypass = LiftBypass;
	Ease[leftLift1].Ease = LiftEase;
	Ease[leftLift2].Ease = LiftEase;
	Ease[rightLift1].Ease = LiftEase;
	Ease[rightLift2].Ease = LiftEase;
	Ease[leftWheelF].Ease = WheelEase;
	Ease[leftWheelR].Ease = WheelEase;
	Ease[rightWheelF].Ease = WheelEase;
	Ease[rightWheelR].Ease = WheelEase;
	startTask(LCD);
}

#include "Vex_Competition_Include.c"   //Main competition background code...do not modify!

/*
-----------------------------ConBot 2014-----------------------------
(Short for Connor Bot 2014)
Written by members of VEX Robotics team 4208 A/B

Everything VEX is so expensive O_O

Reference: http://help.robotc.net/WebHelpVEX/index.htm

-----Instructions/Use-----
Press 5U to toggle between arcade and tank controls.
Default is arcade control mode.
Arcade controls:
Use the right joystick to control movement
Tank controls:
Use the left joystick to control the left wheels
Use the right joystick to control the right wheels

*/

// -----Internal-----
// Defines constants for readability and understandability
// Control modes
/*
const int CONTROL_ARCADE = 1;
const int CONTROL_TANK = 2;
const int CONTROL_ARCADE_OLD = 3;
// Maximum integer for control modes
const int CONTROL_MAX = 1;
// Whether or not to allow the left lift motors to run
bool leftLiftHalt = false;
// Whether or not to allow the right lift motors to run
bool rightLiftHalt = false;
// Holds the last known button state for the 5 Up button
// Used to prevent rapidly toggling control modes while button is held down
bool Btn5UState = false;
*/

#include "Autonomous.c"
#include "User Control.c"
